import{PrismaClient}from"@prisma/client";import bcrypt from"bcryptjs";const db=new PrismaClient();
const vehicles=[
 {title:"Porsche 911 Carrera",category:"Car",location:"San Diego, CA",price:349,description:"A timeless sports car for coast roads and unforgettable weekends.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Porsche_992_Carrera_S_coupe_IMG_5832.jpg/1920px-Porsche_992_Carrera_S_coupe_IMG_5832.jpg",make:"Porsche",model:"911 Carrera",source:"https://commons.wikimedia.org/wiki/File:Porsche_992_Carrera_S_coupe_IMG_5832.jpg"},
 {title:"Winnebago Solis Camper Van",category:"Camper van",location:"Los Angeles, CA",price:229,description:"A fully equipped camper van with pop-top sleeping and a compact galley.",image:"https://www.winnebago.com/Admin/Public/GetImage.ashx?Crop=1&DoNotUpscale=True&FillCanvas=False&Format=WebP&Height=900&Image=%2FFiles%2FImages%2FWinnebagoLife%2Fwinnebago-Solis-off-road.jpg&Quality=85",make:"Winnebago",model:"Solis",source:"https://www.winnebago.com/models/product/motorhomes/camper-van/solis"},
 {title:"Sea Ray Sundancer 320",category:"Boat",location:"San Diego, CA",price:599,description:"A refined cruiser ready for relaxed harbor days with friends and family.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Sea_Ray_Sundancer_320%2C_Interboot_2020%2C_Friedrichshafen_%28IB200044%29.jpg/1920px-Sea_Ray_Sundancer_320%2C_Interboot_2020%2C_Friedrichshafen_%28IB200044%29.jpg",make:"Sea Ray",model:"Sundancer 320",source:"https://commons.wikimedia.org/wiki/File:Sea_Ray_Sundancer_320,_Interboot_2020,_Friedrichshafen_(IB200044).jpg"},
 {title:"Ducati Scrambler Icon",category:"Motorcycle",location:"Palm Springs, CA",price:139,description:"Light, expressive, and perfect for sweeping desert roads.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/2015_Ducati_Scrambler_Icon_right.JPG/1920px-2015_Ducati_Scrambler_Icon_right.JPG",make:"Ducati",model:"Scrambler Icon",source:"https://commons.wikimedia.org/wiki/File:2015_Ducati_Scrambler_Icon_right.JPG"},
 {title:"Polaris RZR Pro XP",category:"UTV",location:"Glamis, CA",price:289,description:"Trail-ready side-by-side performance with safety equipment included.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/2021_Polaris_RZR_Pro_XP.jpg/1920px-2021_Polaris_RZR_Pro_XP.jpg",make:"Polaris",model:"RZR Pro XP",source:"https://commons.wikimedia.org/wiki/File:2021_Polaris_RZR_Pro_XP.jpg"},
 {title:"Polaris Sportsman 850 ATV",category:"ATV",location:"Glamis, CA",price:229,description:"Confident four-wheel trail performance for desert routes and weekend exploration.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Polaris_Sportsman_850.jpg/1920px-Polaris_Sportsman_850.jpg",make:"Polaris",model:"Sportsman 850",source:"https://commons.wikimedia.org/"},
 {title:"Azimut 55 Flybridge Yacht",category:"Luxury",location:"San Diego, CA",price:2499,description:"A private-yacht experience with spacious entertaining areas and a polished coastal finish.",image:"https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1920&q=85",make:"Azimut",model:"55 Flybridge",source:"https://unsplash.com/"},
 {title:"Airstream Flying Cloud",category:"Travel trailer",location:"Joshua Tree, CA",price:199,description:"An iconic aluminum travel trailer with a serene, modern interior.",image:"https://a-us.storyblok.com/f/1023767/1920x1080/c1d7b53f91/1920x1080_flying-cloud-exterior-iso.png",make:"Airstream",model:"Flying Cloud",source:"https://www.airstream.com/travel-trailers/flying-cloud/"},
 {title:"Ford Bronco Wildtrak",category:"SUV",location:"San Diego, CA",price:189,description:"Adventure-ready 4x4 SUV with removable roof and premium trail package.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/2022_Ford_Bronco_Wildtrak%2C_front_3.11.23.jpg/1920px-2022_Ford_Bronco_Wildtrak%2C_front_3.11.23.jpg",make:"Ford",model:"Bronco Wildtrak",source:"https://commons.wikimedia.org/wiki/File:2022_Ford_Bronco_Wildtrak,_front_3.11.23.jpg"},
 {title:"Yamaha WaveRunner VX",category:"Jet ski",location:"Mission Bay, CA",price:119,description:"Responsive personal watercraft, stable and easy to enjoy for a day on the bay.",image:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Yamaha_Waverunner_VX_-_Perissa_-_Santorini_-_Greece_-_01.jpg/1920px-Yamaha_Waverunner_VX_-_Perissa_-_Santorini_-_Greece_-_01.jpg",make:"Yamaha",model:"WaveRunner VX",source:"https://commons.wikimedia.org/wiki/File:Yamaha_Waverunner_VX_-_Perissa_-_Santorini_-_Greece_-_01.jpg"}
];
async function main(){await db.message.deleteMany();await db.review.deleteMany();await db.favorite.deleteMany();await db.booking.deleteMany();await db.photo.deleteMany();await db.listing.deleteMany();await db.user.deleteMany();const hash=await bcrypt.hash("VayroDemo2026!",12);const admin=await db.user.create({data:{email:"admin@vayro.test",passwordHash:hash,name:"Vayro Admin",role:"ADMIN"}});const owner=await db.user.create({data:{email:"owner@vayro.test",passwordHash:hash,name:"Maya Rivers",isOwner:true,bio:"Demo owner account for the investor walkthrough."}});const renter=await db.user.create({data:{email:"renter@vayro.test",passwordHash:hash,name:"Alex Morgan"}});for(let i=0;i<vehicles.length;i++){const v=vehicles[i];const listing=await db.listing.create({data:{slug:`${v.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${i}`,title:v.title,category:v.category,location:v.location,pricePerDay:v.price,securityDeposit:500,description:v.description,features:["Instant owner support","Professionally cleaned","Safety kit"],rules:["No smoking","Return with same fuel level"],deliveryOptions:["Owner pickup","Local delivery available"],details:{year:String(2021+i%4),make:v.make,model:v.model,_photoSource:"VAYRO_REPRESENTATIVE",_isDemo:"true"},status:"PAUSED",ownerId:owner.id,photos:{create:{url:v.image,position:0,alt:`Representative ${v.title} image supplied by Vayro`}}}});if(i<3)await db.review.create({data:{authorId:renter.id,listingId:listing.id,rating:5,comment:"Illustrative investor-demo review; not a live marketplace review."}});if(i===0){const booking=await db.booking.create({data:{listingId:listing.id,renterId:renter.id,startDate:new Date("2026-09-12"),endDate:new Date("2026-09-15"),totalPrice:1047,status:"PENDING",note:"Illustrative investor-demo trip."}});await db.favorite.create({data:{userId:renter.id,listingId:listing.id}});await db.message.create({data:{senderId:renter.id,recipientId:owner.id,bookingId:booking.id,body:"Investor demo message — not a live renter conversation."}});await db.message.create({data:{senderId:owner.id,recipientId:renter.id,bookingId:booking.id,body:"Investor demo reply — no real reservation was created."}})}}console.log({admin:admin.email,owner:owner.email,renter:renter.email,demoListings:vehicles.length})}main().finally(()=>db.$disconnect());
