import{PrismaClient}from"@prisma/client";import bcrypt from"bcryptjs";const db=new PrismaClient();
const vehicles=[
 {title:"Porsche 911 Carrera",category:"Car",location:"San Diego, CA",price:349,description:"A timeless sports car for coast roads and unforgettable weekends.",image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=80",make:"Porsche",model:"911 Carrera"},
 {title:"Winnebago Solis Camper Van",category:"Camper van",location:"Los Angeles, CA",price:229,description:"A fully equipped camper van with pop-top sleeping and a compact galley.",image:"https://www.winnebago.com/Admin/Public/GetImage.ashx?Crop=1&DoNotUpscale=True&FillCanvas=False&Format=WebP&Height=900&Image=%2FFiles%2FImages%2FWinnebagoLife%2Fwinnebago-Solis-off-road.jpg&Quality=85",make:"Winnebago",model:"Solis"},
 {title:"Sea Ray Sundancer 320",category:"Boat",location:"San Diego, CA",price:599,description:"A refined cruiser ready for relaxed harbor days with friends and family.",image:"https://images.boats.com/resize/wp/2/files/2024/03/sea-ray-370-sundance-998x666.jpg",make:"Sea Ray",model:"Sundancer 320"},
 {title:"Ducati Scrambler Icon",category:"Motorcycle",location:"Palm Springs, CA",price:139,description:"Light, expressive, and perfect for sweeping desert roads.",image:"https://images.unsplash.com/photo-1654136682764-53e08ef6ac95?auto=format&fit=crop&w=1400&q=80",make:"Ducati",model:"Scrambler Icon"},
 {title:"Polaris RZR Pro XP",category:"UTV",location:"Glamis, CA",price:289,description:"Trail-ready side-by-side performance with safety equipment included.",image:"https://images.unsplash.com/photo-1517962140171-2dfc01caecb7?auto=format&fit=crop&w=1400&q=80",make:"Polaris",model:"RZR Pro XP"},
 {title:"Airstream Flying Cloud",category:"Travel trailer",location:"Joshua Tree, CA",price:199,description:"An iconic aluminum travel trailer with a serene, modern interior.",image:"https://images.unsplash.com/photo-1619317190381-643a6b28d6e6?auto=format&fit=crop&w=1400&q=80",make:"Airstream",model:"Flying Cloud"},
 {title:"Ford Bronco Wildtrak",category:"SUV",location:"San Diego, CA",price:189,description:"Adventure-ready 4x4 SUV with removable roof and premium trail package.",image:"https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80",make:"Ford",model:"Bronco Wildtrak"},
 {title:"Yamaha WaveRunner VX",category:"Jet ski",location:"Mission Bay, CA",price:119,description:"Responsive personal watercraft, stable and easy to enjoy for a day on the bay.",image:"https://images.unsplash.com/photo-1524061508355-90afbf7fcf03?auto=format&fit=crop&w=1400&q=80",make:"Yamaha",model:"WaveRunner VX"}
];
async function main(){await db.message.deleteMany();await db.review.deleteMany();await db.favorite.deleteMany();await db.booking.deleteMany();await db.photo.deleteMany();await db.listing.deleteMany();await db.user.deleteMany();const hash=await bcrypt.hash("VayroDemo2026!",12);const admin=await db.user.create({data:{email:"admin@vayro.test",passwordHash:hash,name:"Vayro Admin",role:"ADMIN"}});const owner=await db.user.create({data:{email:"owner@vayro.test",passwordHash:hash,name:"Maya Rivers",isOwner:true,bio:"Weekend explorer sharing a carefully maintained fleet."}});const renter=await db.user.create({data:{email:"renter@vayro.test",passwordHash:hash,name:"Alex Morgan"}});for(let i=0;i<vehicles.length;i++){const v=vehicles[i];const listing=await db.listing.create({data:{slug:`${v.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${i}`,title:v.title,category:v.category,location:v.location,pricePerDay:v.price,securityDeposit:500,description:v.description,features:["Instant owner support","Professionally cleaned","Safety kit"],rules:["No smoking","Return with same fuel level"],deliveryOptions:["Owner pickup","Local delivery available"],details:{year:String(2021+i%4),make:v.make,model:v.model,_photoSource:"VAYRO_REPRESENTATIVE"},ownerId:owner.id,photos:{create:{url:v.image,position:0,alt:`Representative ${v.title} image supplied by Vayro`}}}});if(i<3)await db.review.create({data:{authorId:renter.id,listingId:listing.id,rating:5,comment:"Wonderful ride and a thoughtful owner. Everything was exactly as described."}});if(i===0){const booking=await db.booking.create({data:{listingId:listing.id,renterId:renter.id,startDate:new Date("2026-09-12"),endDate:new Date("2026-09-15"),totalPrice:1047,status:"PENDING",note:"Anniversary coastal drive."}});await db.favorite.create({data:{userId:renter.id,listingId:listing.id}});await db.message.create({data:{senderId:renter.id,recipientId:owner.id,bookingId:booking.id,body:"Hi Maya! Is the car available for a coastal trip?"}});await db.message.create({data:{senderId:owner.id,recipientId:renter.id,bookingId:booking.id,body:"It is! I’ll review your request today."}})}}console.log({admin:admin.email,owner:owner.email,renter:renter.email,listings:vehicles.length})}main().finally(()=>db.$disconnect());
