import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { listingSchema } from "@/lib/validation";
import { isRepresentative, resolveListingPhotos } from "@/lib/listing-images";
import { resolveCatalogSelection } from "@/lib/catalog-selection";
async function own(id:string){const user=await requireUser(),listing=await db.listing.findUnique({where:{id}});if(!listing||(listing.ownerId!==user.id&&user.role!=="ADMIN"))throw new Error("FORBIDDEN");return listing;}
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;await own(id);const raw=await request.json();if(raw.status){if(!["ACTIVE","PAUSED"].includes(raw.status))throw new Error("INVALID");if(raw.status==="ACTIVE"){const actualPhotos=await db.photo.count({where:{listingId:id,uploadedByOwner:true,isRepresentative:false}});if(!actualPhotos)return NextResponse.json({error:"Upload an actual vehicle photo before activating this listing"},{status:400});}await db.listing.update({where:{id},data:{status:raw.status}});return NextResponse.json({ok:true});}const parsed=listingSchema.safeParse(raw);if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0].message},{status:400});const{photoUrls:submitted,...rest}=parsed.data,selected=await resolveCatalogSelection(raw.catalogModelId,rest.details),resolved=resolveListingPhotos(rest.category,submitted,selected.details),representative=isRepresentative(resolved.details),draft=raw.statusIntent==="DRAFT";await db.$transaction([db.photo.deleteMany({where:{listingId:id}}),db.listing.update({where:{id},data:{...rest,details:resolved.details,catalogModelId:selected.catalogModelId,status:draft||representative?"PAUSED":"ACTIVE",photos:{create:resolved.photoUrls.map((url,position)=>({url,position,uploadedByOwner:!representative,isRepresentative:representative,sourceUrl:representative?url:null,license:representative?"Vayro photo-needed graphic; not a vehicle photo":null,alt:representative?`${[rest.details.year,rest.details.make,rest.details.model].filter(Boolean).join(" ")||rest.category} needs an owner photo`:rest.title}))}}})]);return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Forbidden or invalid request"},{status:403});}}
export async function DELETE(_:NextRequest,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;await own(id);const bookingCount=await db.booking.count({where:{listingId:id}});if(bookingCount){await db.listing.update({where:{id},data:{status:"DISABLED"}});return NextResponse.json({ok:true,archived:true});}await db.listing.delete({where:{id}});return NextResponse.json({ok:true,archived:false});}catch{return NextResponse.json({error:"Forbidden"},{status:403});}}
export const POST=PATCH;
