import Link from "next/link";
import { db } from "@/lib/db";
import { ListingCard } from "@/components/ListingCard";
import { RecentlyViewed } from "@/components/ClientActions";
import { AdSense } from "@/components/AdSense";
import { getUser } from "@/lib/auth";
export default async function Home() { const [listings, listingCount, reviewCount, tripCount,user] = await Promise.all([db.listing.findMany({ where: { status: "ACTIVE" }, include: { photos: true, reviews: true }, take: 6, orderBy: { createdAt: "desc" } }),db.listing.count({where:{status:"ACTIVE"}}),db.review.count(),db.booking.count({where:{status:{in:["PAID","ACTIVE","COMPLETED"]}}}),getUser()]); const showAds=user?.subscriptionStatus!=="ACTIVE",publisherId=process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID||"",slotId=process.env.NEXT_PUBLIC_ADSENSE_SLOT_ID||""; return <>
  <section className="hero"><div><span className="eyebrow">THE PEER-TO-PEER ADVENTURE MARKETPLACE</span><h1>Rent anything<br/>that <em>moves.</em></h1><p>Vayro connects people who need a ride with local owners who have one to share. Book cars, trucks, SUVs, luxury vehicles, RVs, camper vans, trailers, boats, jet skis, motorcycles, ATVs, UTVs, and more—with clear pricing, verified profiles, and protected checkout.</p><div className="heroactions"><Link className="button bright" href="/browse">Find a vehicle</Link><Link className="button glass" href="/owner/new">List your vehicle</Link><Link className="button glass" href="/demo">Investor demo</Link></div><form action="/browse" className="search"><label>Where<input name="location" placeholder="City or destination"/></label><label>From<input name="start" type="date"/></label><label>Until<input name="end" type="date"/></label><button>Search</button></form></div></section>
  <section className="trustbar"><span>Rent from local owners</span><span>Earn by sharing your vehicle</span><span>Identity-gated bookings</span><Link href="/browse?photos=representative">Browse every vehicle category</Link></section>
  <section className="proof" aria-label="Vayro marketplace activity"><div><b>{listingCount}+</b><span>rides ready to explore</span></div><div><b>{tripCount}+</b><span>confirmed adventures</span></div><div><b>{reviewCount}+</b><span>community reviews</span></div></section>
  {showAds&&<AdSense publisherId={publisherId} slotId={slotId}/>}
  <section className="section"><div className="sectionhead"><div><span className="eyebrow">START EXPLORING</span><h2>Made for every kind of escape</h2></div><Link href="/browse">View all →</Link></div><div className="categories">{[["Cars","Car","⌁"],["RVs","RV","⌂"],["Boats","Boat","≈"],["Motorcycles","Motorcycle","◒"],["ATVs","ATV","✣"],["UTVs","UTV","◈"],["Vayro Lux","Luxury","◆"],["Trailers","Travel trailer","△"]].map(([label,category,icon])=><Link key={label} href={category==="Luxury"?"/lux":`/browse?category=${category}`}><b>{icon}</b>{label}</Link>)}</div><div className="grid">{listings.map(l=><ListingCard key={l.id} l={l}/>)}</div></section>
  <RecentlyViewed />
  <section className="how"><span className="eyebrow">HOW VAYRO WORKS</span><h2>From search to road in four steps.</h2><div><article><b>01</b><h3>Discover</h3><p>Filter by dates, destination, category, features, delivery, and total price.</p></article><article><b>02</b><h3>Get verified</h3><p>Complete secure hosted identity checks. Sensitive ID data is never stored by Vayro.</p></article><article><b>03</b><h3>Request and pay</h3><p>The owner accepts, then Stripe handles payment and marketplace payouts.</p></article><article><b>04</b><h3>Document the trip</h3><p>Check-in and return reports protect both sides with current condition photos.</p></article></div></section>
  <section className="promise"><span className="eyebrow">FOR OWNERS</span><h2>Turn your vehicle into a peer-to-peer business.</h2><p>Share a car that sits idle, a boat that deserves more weekends, or an RV ready for the next adventure. You set the price, calendar, rules, delivery options, and who you accept.</p><div><p><b>You control the fee</b><br/>Choose whether the renter pays, you absorb it, or split it evenly.</p><p><b>You control the calendar</b><br/>Pause anytime, block dates, and accept only trips that work for you.</p><p><b>Built for trust</b><br/>Identity, vehicle verification, trip reports, messaging, and reviews in one place.</p></div><Link href="/owner/new" className="button">List your vehicle</Link></section>
  </>; }
