import Link from "next/link";
import { db } from "@/lib/db";
import { ListingCard } from "@/components/ListingCard";
import { RecentlyViewed } from "@/components/ClientActions";
export default async function Home() { const [listings, listingCount, reviewCount, tripCount] = await Promise.all([db.listing.findMany({ where: { status: "ACTIVE" }, include: { photos: true, reviews: true }, take: 6, orderBy: { createdAt: "desc" } }),db.listing.count({where:{status:"ACTIVE"}}),db.review.count(),db.booking.count({where:{status:{in:["PAID","ACTIVE","COMPLETED"]}}})]); return <>
  <section className="hero"><div><span className="eyebrow">THE OPEN ROAD, UNLOCKED</span><h1>Rent anything<br/>that <em>moves.</em></h1><p>Book cars, RVs, boats, motorcycles, and outdoor vehicles from local owners—with clear pricing and protected checkout.</p><div className="heroactions"><Link className="button bright" href="/browse">Find a vehicle</Link><Link className="button glass" href="/owner/new">List your vehicle</Link></div><form action="/browse" className="search"><label>Where<input name="location" placeholder="City or destination"/></label><label>From<input name="start" type="date"/></label><label>Until<input name="end" type="date"/></label><button>Search</button></form></div></section>
  <section className="trustbar"><span>Identity-gated bookings</span><span>Secure Stripe checkout</span><span>Verified vehicle workflow</span><span>10% standard · 7.5% Plus</span></section>
  <section className="proof" aria-label="Vayro marketplace activity"><div><b>{listingCount}+</b><span>rides ready to explore</span></div><div><b>{tripCount}+</b><span>confirmed adventures</span></div><div><b>{reviewCount}+</b><span>community reviews</span></div></section>
  <section className="section"><div className="sectionhead"><div><span className="eyebrow">START EXPLORING</span><h2>Made for every kind of escape</h2></div><Link href="/browse">View all →</Link></div><div className="categories">{["Cars","RVs","Boats","Motorcycles","Off-road","Trailers"].map((x,i)=><Link key={x} href={`/browse?category=${x.replace(/s$/,"")}`}><b>{["⌁","⌂","≈","◒","✣","△"][i]}</b>{x}</Link>)}</div><div className="grid">{listings.map(l=><ListingCard key={l.id} l={l}/>)}</div></section>
  <RecentlyViewed />
  <section className="how"><span className="eyebrow">HOW VAYRO WORKS</span><h2>From search to road in four steps.</h2><div><article><b>01</b><h3>Discover</h3><p>Filter by dates, destination, category, features, delivery, and total price.</p></article><article><b>02</b><h3>Get verified</h3><p>Complete secure hosted identity checks. Sensitive ID data is never stored by Vayro.</p></article><article><b>03</b><h3>Request and pay</h3><p>The owner accepts, then Stripe handles payment and marketplace payouts.</p></article><article><b>04</b><h3>Document the trip</h3><p>Check-in and return reports protect both sides with current condition photos.</p></article></div></section>
  <section className="promise"><span className="eyebrow">FOR OWNERS</span><h2>Turn your vehicle into a business.</h2><div><p><b>You control the fee</b><br/>Choose whether the renter pays, you absorb it, or split it evenly.</p><p><b>You control the calendar</b><br/>Pause anytime, block dates, and accept only trips that work for you.</p><p><b>Built for trust</b><br/>Identity, vehicle verification, trip reports, messaging, and reviews in one place.</p></div><Link href="/owner/new" className="button">List your vehicle</Link></section>
  </>; }
