"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { VehicleCatalogFields } from "./VehicleCatalogFields";
export type VehicleDraft = { id: string; slug: string; title: string; description: string; category: string; location: string; pricePerDay: number; securityDeposit: number; feePayer: "RENTER"|"OWNER"|"SPLIT"; catalogModelId?: string|null; features: string[]; rules: string[]; deliveryOptions: string[]; details: Record<string,string>; photos: {url:string}[] };
async function compress(files: File[]) { if (files.length > 6) throw new Error("Upload up to 6 photos"); return Promise.all(files.filter(x => x.size).map(file => new Promise<string>((resolve, reject) => { if (!/^image\/(jpeg|png|webp)$/.test(file.type)) return reject(new Error("Use JPEG, PNG, or WebP photos")); if (file.size > 8e6) return reject(new Error("Each photo must be under 8 MB")); const image = new Image(), url = URL.createObjectURL(file); image.onload = () => { const scale = Math.min(1, 1600/image.width, 1200/image.height), canvas = document.createElement("canvas"); canvas.width = Math.round(image.width*scale); canvas.height = Math.round(image.height*scale); canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height); URL.revokeObjectURL(url); const value=canvas.toDataURL("image/webp",.78); if (value.length>16e5) reject(new Error("Compressed photo is too large")); else resolve(value); }; image.onerror=()=>reject(new Error("Could not read a photo")); image.src=url; })) ); }
export function VehicleListingForm({ listing }: { listing?: VehicleDraft }) {
  const router=useRouter(), [error,setError]=useState(""), [busy,setBusy]=useState(false), csv=(form:FormData,key:string)=>String(form.get(key)||"").split(",").map(x=>x.trim()).filter(Boolean);
  return <form className="stack panel" onSubmit={async event => { event.preventDefault(); setBusy(true); setError(""); const form=new FormData(event.currentTarget),submitter=(event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null,statusIntent=submitter?.value||"PUBLISH"; try { const uploaded=await compress(form.getAll("photoFiles").filter(x=>x instanceof File) as File[]), linked=csv(form,"photos"), photoUrls=uploaded.length||linked.length?[...uploaded,...linked]:(listing?.photos.map(x=>x.url)||[]), details=Object.fromEntries(["year","make","model","vin","licensePlate","mileage","seats","transmission","fuelType","weeklyDiscount","monthlyDiscount"].map(key=>[key,String(form.get(key)||"")])); const body={ title:form.get("title"), description:form.get("description"), category:form.get("category"), location:form.get("location"), pricePerDay:form.get("pricePerDay"), securityDeposit:form.get("securityDeposit"), feePayer:form.get("feePayer"), catalogModelId:form.get("catalogModelId")||null, features:csv(form,"features"), rules:csv(form,"rules"), deliveryOptions:csv(form,"deliveryOptions"), photoUrls, details,statusIntent }; const response=await fetch(listing?`/api/listings/${listing.id}`:"/api/listings",{method:listing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json(); if(!response.ok)throw new Error(result.error); router.push(statusIntent==="DRAFT"?"/owner":`/listings/${listing?.slug||result.slug}`); } catch(e) { setError((e as Error).message); setBusy(false); } }}>
    <h2>{listing?"Edit vehicle":"Post a real vehicle"}</h2><p className="muted">Select trusted catalog data when available. Custom and antique vehicles can still be entered manually. VINs and plates remain private.</p>
    <div className="formgrid"><label>Listing title<input name="title" defaultValue={listing?.title} required/></label><label>Category<select name="category" defaultValue={listing?.category}>{["Car","Truck","SUV","Luxury","RV","Camper van","Travel trailer","Boat","Jet ski","Motorcycle","ATV","UTV","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label>Location<input name="location" defaultValue={listing?.location} required/></label><label>Price / day<input name="pricePerDay" type="number" min="1" defaultValue={listing?.pricePerDay} required/></label><label>Security deposit<input name="securityDeposit" type="number" min="0" defaultValue={listing?.securityDeposit??0} required/></label><label>Marketplace fee<select name="feePayer" defaultValue={listing?.feePayer||"RENTER"}><option value="RENTER">Renter pays fee</option><option value="OWNER">I absorb fee</option><option value="SPLIT">Split fee 50/50</option></select></label><VehicleCatalogFields details={listing?.details} catalogModelId={listing?.catalogModelId}/><label>License plate<input name="licensePlate" maxLength={16} defaultValue={listing?.details.licensePlate}/></label><label>Mileage / hours<input name="mileage" inputMode="numeric" defaultValue={listing?.details.mileage}/></label><label>Seats<input name="seats" type="number" min="1" max="30" defaultValue={listing?.details.seats}/></label><label>Transmission<select name="transmission" defaultValue={listing?.details.transmission}><option value="">Not applicable</option><option>Automatic</option><option>Manual</option></select></label><label>Fuel / power<input name="fuelType" placeholder="Gas, diesel, electric…" defaultValue={listing?.details.fuelType}/></label></div>
    <div className="discounts"><label>Weekly discount %<input name="weeklyDiscount" type="number" min="0" max="50" defaultValue={listing?.details.weeklyDiscount||"10"}/><small>Suggested: 10%</small></label><label>Monthly discount %<input name="monthlyDiscount" type="number" min="0" max="60" defaultValue={listing?.details.monthlyDiscount||"20"}/><small>Suggested: 20%</small></label></div><label>Description<textarea name="description" defaultValue={listing?.description} minLength={30} required/></label><label className="uploadbox">Upload actual vehicle photos <small>Strongly recommended: up to 6 JPEG, PNG, or WebP files.</small><input name="photoFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple/></label><div className="photoguide"><b>Photo checklist</b><span>□ Front three-quarter</span><span>□ Rear three-quarter</span><span>□ Interior and seats</span><span>□ Dashboard and mileage</span><span>□ Tires and cargo space</span><span>□ Existing wear or damage</span></div><label>Or image URLs<textarea name="photos" defaultValue={listing?.photos.filter(x=>!x.url.startsWith("data:")).map(x=>x.url).join(", ")}/></label><p className="notice"><b>No camera? You may still publish.</b> Vayro will show a branded make/model representation—not a photo of your actual vehicle—and warn renters again before requesting. Using false or borrowed photos to deceive renters can result in permanent removal, refunds, and lawful payout holds.</p><label>Features<input name="features" defaultValue={listing?.features.join(", ")}/></label><label>Rules<input name="rules" defaultValue={listing?.rules.join(", ")}/></label><label>Delivery options<input name="deliveryOptions" defaultValue={listing?.deliveryOptions.join(", ")}/></label>{error&&<p className="error">{error}</p>}<div className="actions"><button className="outline" name="intent" value="DRAFT" disabled={busy}>Save draft</button><button className="button" name="intent" value="PUBLISH" disabled={busy}>{busy?"Saving vehicle…":listing?"Save and publish":"Publish vehicle"}</button></div>
  </form>;
}
